#!/usr/bin/env node
// Generate a Paperclip config.json (plus local .env and secrets key) from environment
// variables so `paperclipai onboard` is not required for a Docker/Coolify deployment.
//
// This script is intentionally self-contained and only uses Node builtins so it can run
// before dependencies are guaranteed to be importable.

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

function env(name, fallback) {
  const value = process.env[name];
  if (value === undefined || value.trim().length === 0) return fallback;
  return value.trim();
}

function envBool(name, fallback) {
  const value = env(name);
  if (value === undefined) return fallback;
  const lower = value.toLowerCase();
  return lower === "true" || lower === "1" || lower === "yes";
}

function envNumber(name, fallback, { min, max } = {}) {
  const value = env(name);
  if (value === undefined) return fallback;
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return fallback;
  if (min !== undefined && parsed < min) return min;
  if (max !== undefined && parsed > max) return max;
  return parsed;
}

function expandHome(value) {
  if (value === "~" || value.startsWith("~/")) {
    return path.resolve(process.env.HOME || "/paperclip", value === "~" ? "" : value.slice(2));
  }
  return path.resolve(value);
}

const HOME = env("PAPERCLIP_HOME", env("HOME", "/paperclip"));
const INSTANCE_ID = env("PAPERCLIP_INSTANCE_ID", "default");
const INSTANCE_ROOT = path.resolve(HOME, "instances", INSTANCE_ID);
const CONFIG_PATH = env("PAPERCLIP_CONFIG", path.resolve(INSTANCE_ROOT, "config.json"));
const CONFIG_DIR = path.dirname(CONFIG_PATH);
const ENV_PATH = path.resolve(CONFIG_DIR, ".env");
const SECRETS_KEY_PATH = path.resolve(CONFIG_DIR, "secrets", "master.key");

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFileRestricted(filePath, content) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, { mode: 0o600 });
  try {
    fs.chmodSync(filePath, 0o600);
  } catch {
    // best effort in restricted environments
  }
}

function generateHex(bytes) {
  return crypto.randomBytes(bytes).toString("hex");
}

function generateBase64(bytes) {
  return crypto.randomBytes(bytes).toString("base64");
}

function ensureAgentJwtSecret() {
  if (process.env.PAPERCLIP_AGENT_JWT_SECRET) {
    return { secret: process.env.PAPERCLIP_AGENT_JWT_SECRET, created: false };
  }

  let existing = null;
  if (fs.existsSync(ENV_PATH)) {
    const contents = fs.readFileSync(ENV_PATH, "utf8");
    const match = contents.match(/^PAPERCLIP_AGENT_JWT_SECRET=(.+)$/m);
    if (match) {
      existing = match[1].replace(/^["']|["']$/g, "").trim();
    }
  }

  if (existing) {
    return { secret: existing, created: false };
  }

  const secret = generateHex(32);
  const lines = [
    "# Paperclip environment variables",
    "# Generated by Paperclip Docker init",
    `PAPERCLIP_AGENT_JWT_SECRET=${secret}`,
    "",
  ];
  writeFileRestricted(ENV_PATH, lines.join("\n"));
  return { secret, created: true };
}

function ensureSecretsKey() {
  const provider = env("PAPERCLIP_SECRETS_PROVIDER", "local_encrypted");
  if (provider !== "local_encrypted") return { status: "skipped_provider", path: null };
  if (process.env.PAPERCLIP_SECRETS_MASTER_KEY) return { status: "skipped_env", path: null };

  const keyFilePath = env("PAPERCLIP_SECRETS_MASTER_KEY_FILE", SECRETS_KEY_PATH);
  const resolved = expandHome(keyFilePath);
  if (fs.existsSync(resolved)) {
    return { status: "existing", path: resolved };
  }
  writeFileRestricted(resolved, generateBase64(32));
  return { status: "created", path: resolved };
}

function inferBindMode(host) {
  const lower = host.toLowerCase();
  if (lower === "127.0.0.1" || lower === "localhost" || lower === "::1") return "loopback";
  if (lower === "0.0.0.0" || lower === "::") return "lan";
  return "custom";
}

function buildConfig() {
  const deploymentMode = env("PAPERCLIP_DEPLOYMENT_MODE", "authenticated");
  const deploymentExposure = env("PAPERCLIP_DEPLOYMENT_EXPOSURE", "public");
  const host = env("HOST", "0.0.0.0");
  const port = envNumber("PORT", 3100);
  const bind = inferBindMode(host);

  const publicUrl =
    env("PAPERCLIP_PUBLIC_URL") ||
    env("PAPERCLIP_AUTH_PUBLIC_BASE_URL") ||
    env("BETTER_AUTH_URL") ||
    env("BETTER_AUTH_BASE_URL");

  const authBaseUrlMode = env("PAPERCLIP_AUTH_BASE_URL_MODE", publicUrl ? "explicit" : "auto");

  const allowedHostnamesRaw = env("PAPERCLIP_ALLOWED_HOSTNAMES", "");
  const allowedHostnamesSet = new Set(
    allowedHostnamesRaw
      .split(",")
      .map((h) => h.trim().toLowerCase())
      .filter(Boolean),
  );
  if (publicUrl) {
    try {
      allowedHostnamesSet.add(new URL(publicUrl).hostname.toLowerCase());
    } catch {
      // ignore malformed URL
    }
  }
  const allowedHostnames = Array.from(allowedHostnamesSet);

  const databaseUrl = env("DATABASE_URL");
  const databaseMode = databaseUrl ? "postgres" : "embedded-postgres";

  const storageProvider = env("PAPERCLIP_STORAGE_PROVIDER", "local_disk");
  const secretsProvider = env("PAPERCLIP_SECRETS_PROVIDER", "local_encrypted");
  const secretsStrictMode = envBool("PAPERCLIP_SECRETS_STRICT_MODE", deploymentMode === "authenticated");

  const config = {
    $meta: {
      version: 1,
      updatedAt: new Date().toISOString(),
      source: "onboard",
    },
    database: {
      mode: databaseMode,
      ...(databaseUrl ? { connectionString: databaseUrl } : {}),
      embeddedPostgresDataDir: path.resolve(INSTANCE_ROOT, "db"),
      embeddedPostgresPort: 54329,
      backup: {
        enabled: envBool("PAPERCLIP_DB_BACKUP_ENABLED", true),
        intervalMinutes: envNumber("PAPERCLIP_DB_BACKUP_INTERVAL_MINUTES", 60, { min: 1 }),
        retentionDays: envNumber("PAPERCLIP_DB_BACKUP_RETENTION_DAYS", 7, { min: 1 }),
        dir: expandHome(env("PAPERCLIP_DB_BACKUP_DIR", path.resolve(INSTANCE_ROOT, "data", "backups"))),
      },
    },
    logging: {
      mode: "file",
      logDir: expandHome(env("PAPERCLIP_LOG_DIR", path.resolve(INSTANCE_ROOT, "logs"))),
    },
    server: {
      deploymentMode,
      exposure: deploymentExposure,
      bind,
      ...(bind === "custom" ? { customBindHost: host } : {}),
      host,
      port,
      allowedHostnames,
      serveUi: envBool("SERVE_UI", true),
    },
    telemetry: {
      enabled: envBool("PAPERCLIP_TELEMETRY_ENABLED", true),
    },
    auth: {
      baseUrlMode: authBaseUrlMode,
      disableSignUp: envBool("PAPERCLIP_AUTH_DISABLE_SIGN_UP", false),
      ...(publicUrl ? { publicBaseUrl: publicUrl } : {}),
    },
    storage: {
      provider: storageProvider,
      localDisk: {
        baseDir: expandHome(
          env("PAPERCLIP_STORAGE_LOCAL_DIR", path.resolve(INSTANCE_ROOT, "data", "storage")),
        ),
      },
      s3: {
        bucket: env("PAPERCLIP_STORAGE_S3_BUCKET", "paperclip"),
        region: env("PAPERCLIP_STORAGE_S3_REGION", "us-east-1"),
        endpoint: env("PAPERCLIP_STORAGE_S3_ENDPOINT", undefined),
        prefix: env("PAPERCLIP_STORAGE_S3_PREFIX", ""),
        forcePathStyle: envBool("PAPERCLIP_STORAGE_S3_FORCE_PATH_STYLE", false),
      },
    },
    secrets: {
      provider: secretsProvider,
      strictMode: secretsStrictMode,
      localEncrypted: {
        keyFilePath: expandHome(
          env("PAPERCLIP_SECRETS_MASTER_KEY_FILE", path.resolve(INSTANCE_ROOT, "secrets", "master.key")),
        ),
      },
    },
  };

  return config;
}

function main() {
  ensureDir(CONFIG_DIR);

  const jwt = ensureAgentJwtSecret();
  const key = ensureSecretsKey();
  const config = buildConfig();

  const configExists = fs.existsSync(CONFIG_PATH);
  if (configExists) {
    console.log(`[paperclip-init] config already exists at ${CONFIG_PATH}; leaving unchanged`);
  } else {
    writeFileRestricted(CONFIG_PATH, JSON.stringify(config, null, 2) + "\n");
    console.log(`[paperclip-init] config: ${CONFIG_PATH}`);
  }
  if (jwt.created) {
    console.log(`[paperclip-init] created PAPERCLIP_AGENT_JWT_SECRET in ${ENV_PATH}`);
  }
  if (key.status === "created") {
    console.log(`[paperclip-init] created secrets key at ${key.path}`);
  }
}

main();
